name: base32_codec
description: A dependency free library for encoding and decoding Base32 data.
version: 1.0.0
repository: https://github.com/dropbear-software/base32_codec
issue_tracker: https://github.com/dropbear-software/base32_codec/issues
topics:
  - base32
  - rfc4648
  - codec

environment:
  sdk: ^3.9.0

dev_dependencies:
  benchmark_harness: ^2.3.1
  lints: ^6.0.0
  test: ^1.25.6
